# Generated by Django 5.2.9 on 2025-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copiers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copier',
            name='created_at',
        ),
        migrations.AddField(
            model_name='copier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='copier',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='copier',
            name='color_counter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='copier',
            name='mono_counter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='copier',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='copier',
            name='total_counter',
            field=models.IntegerField(),
        ),
    ]
